import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        <main className="container mx-auto max-w-full pt-24 flex-grow">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
