import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const ProductSans = localFont({
  src: [
    {
      path: "../public/fonts/productSans/ProductSans-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/productSans/ProductSans-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/productSans/ProductSans-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ProductSans.className}>
        <Header />
        <main className="container mx-auto max-w-full pt-24 flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
